### PR TITLE
Check if the FINISH_REQUEST const exists

### LINKED ISSUE #8: onKernelFinishRequest raises an FATAL ERROR when using Symfony 2.3 standard edition
PHP Fatal error:  Undefined class constant 'FINISH_REQUEST'

This constant was introduced with Symfony2.4 

http://api.symfony.com/2.3/Symfony/Component/HttpKernel/KernelEvents.html
http://api.symfony.com/2.4/Symfony/Component/HttpKernel/KernelEvents.html

Shouldn't we let the user declare this method when needed?

### PR DESCRIPTION
**Pull request by benja-M-1**
resolve #8

### CODE REVIEW

File: EventListener/RouterListener.php [hunk 1]
```diff
@@ -84,9 +84,14 @@ public function onKernelFinishRequest(FinishRequestEvent $event)
      */
     public static function getSubscribedEvents()
     {
-        return array(
+        $listeners = array(
             KernelEvents::REQUEST => array(array('onKernelRequest', 31)),
-            KernelEvents::FINISH_REQUEST => array(array('onKernelFinishRequest', 0)),
         );
+
+        if (defined('KernelEvents::FINISH_REQUEST')) {
```
Comment (stof) [inline EventListener/RouterListener.php]: does not work. It needs to be the FQCN
